from __future__ import annotations
from typing import List, Optional

class FilesBatchIterator:
    def __init__(self, directory: str, batch_size: int) -> None: ...
    def __iter__(self) -> "FilesBatchIterator": ...
    def __next__(self) -> Optional[List[bytes]]: ...
    def __len__(self) -> int: ...

class FlattenFilesBatchIterator:
    def __init__(self, directory: str, batch_size: int) -> None: ...
    def __iter__(self) -> "FlattenFilesBatchIterator": ...
    def __next__(self) -> Optional[bytes]: ...
    def __len__(self) -> int: ...
