from __future__ import annotations
from typing import List, Optional


class FileData:
    path: str
    content: bytes

    def __len__(self) -> int: ...


class FilesBatchIterator:
    def __init__(self, directory: str, batch_size: int) -> None: ...

    def __iter__(self) -> "FilesBatchIterator": ...

    def __next__(self) -> Optional[List[FileData]]: ...

    def __len__(self) -> int: ...


class FlattenFilesIterator:
    def __init__(self, directory: str) -> None: ...

    def __iter__(self) -> "FlattenFilesIterator": ...

    def __next__(self) -> Optional[FileData]: ...

    def __len__(self) -> int: ...
